// Friendly aliases over the generated types — type-checked, so a schema that
// vanishes from generation breaks loudly at tsc time. Never a hand-written
// mirror of a backend shape; the generated file is the single source.
import type { components } from './generated/api'

export type AddDungeon = components['schemas']['AddDungeon']
export type AddFeature = components['schemas']['AddFeature']
export type AddLevel = components['schemas']['AddLevel']
export type AddTransition = components['schemas']['AddTransition']
export type Adventure = components['schemas']['Adventure']
export type Alignment = components['schemas']['Alignment']
export type ApiError = components['schemas']['ApiError']
export type ApiErrorDetail = components['schemas']['ApiErrorDetail']
export type AreaSpec = components['schemas']['AreaSpec']
export type AreaTreasureSpec = components['schemas']['AreaTreasureSpec']
export type CatalogItem = components['schemas']['CatalogItem']
export type CatalogMonster = components['schemas']['CatalogMonster']
export type CatalogTreasureType = components['schemas']['CatalogTreasureType']
export type Coins = components['schemas']['Coins']
export type Condition = components['schemas']['Condition']
export type CreateArea = components['schemas']['CreateArea']
export type Diagnostics = components['schemas']['Diagnostics']
export type EncounterTable = components['schemas']['EncounterTable']
export type EncounterTableCatalogResponse = components['schemas']['EncounterTableCatalogResponse']
export type EncounterTableRow = components['schemas']['EncounterTableRow']
export type EquipmentCatalogResponse = components['schemas']['EquipmentCatalogResponse']
export type DoorSpec = components['schemas']['DoorSpec']
export type DungeonSpec = components['schemas']['DungeonSpec']
export type Edge = components['schemas']['Edge']
export type ExportResult = components['schemas']['ExportResult']
export type FeatureSpec = components['schemas']['FeatureSpec']
export type Finding = components['schemas']['Finding']
export type ImportedArea = components['schemas']['ImportedArea']
export type ImportedGeometry = components['schemas']['ImportedGeometry']
export type ImportedLevel = components['schemas']['ImportedLevel']
export type ImporterInfo = components['schemas']['ImporterInfo']
export type ImporterListResponse = components['schemas']['ImporterListResponse']
export type KeyedEncounter = components['schemas']['KeyedEncounter']
export type KeyedMonster = components['schemas']['KeyedMonster']
export type LevelSpec = components['schemas']['LevelSpec']
export type MonsterCatalogResponse = components['schemas']['MonsterCatalogResponse']
export type MonsterEncounterEntry = components['schemas']['MonsterEncounterEntry']
export type MonsterHitDice = components['schemas']['MonsterHitDice']
export type MonsterTemplate = components['schemas']['MonsterTemplate']

// Phase 4: the stat-block editor's nested models — osrlib's own shapes riding
// the generated types, never hand-mirrored.
export type AcAlternate = components['schemas']['AcAlternate']
export type AlignmentSpec = components['schemas']['AlignmentSpec']
export type AttackRoutine = components['schemas']['AttackRoutine']
export type MonsterAttack = components['schemas']['MonsterAttack']
export type MovementMode = components['schemas']['MovementMode']
export type MonsterSaves = components['schemas']['MonsterSaves']
export type SavingThrows = components['schemas']['SavingThrows']
export type MoraleAlternate = components['schemas']['MoraleAlternate']
export type XpNote = components['schemas']['XpNote']
export type NumberAppearing = components['schemas']['NumberAppearing']
export type NumberAppearingValue = components['schemas']['NumberAppearingValue']
export type TreasureRef = components['schemas']['TreasureRef']
export type MonsterAbility = components['schemas']['MonsterAbility']
export type Defenses = components['schemas']['Defenses']
export type DamageReduction = components['schemas']['DamageReduction']
export type EnergyDefense = components['schemas']['EnergyDefense']
export type DamageKey = components['schemas']['DamageKey']
export type Element = components['schemas']['Element']
export type NpcPartyEncounterEntry = components['schemas']['NpcPartyEncounterEntry']
export type OpBatch = components['schemas']['OpBatch']
export type OpBatchResult = components['schemas']['OpBatchResult']
export type ProjectListResponse = components['schemas']['ProjectListResponse']
export type ProjectState = components['schemas']['ProjectState']
export type PublishResult = components['schemas']['PublishResult']
export type ReactionResult = components['schemas']['ReactionResult']
export type RecentProject = components['schemas']['RecentProject']
export type RemoveArea = components['schemas']['RemoveArea']
export type RemoveDungeon = components['schemas']['RemoveDungeon']
export type RemoveFeature = components['schemas']['RemoveFeature']
export type RemoveLevel = components['schemas']['RemoveLevel']
export type RemoveTransition = components['schemas']['RemoveTransition']
export type RenameDungeon = components['schemas']['RenameDungeon']
export type RenumberLevel = components['schemas']['RenumberLevel']
export type ResizeLevel = components['schemas']['ResizeLevel']
export type SaveCategory = components['schemas']['SaveCategory']
export type SaveSpec = components['schemas']['SaveSpec']
export type SetAdventureField = components['schemas']['SetAdventureField']
export type SetAreaCells = components['schemas']['SetAreaCells']
export type SetAreaField = components['schemas']['SetAreaField']
export type SetDungeonField = components['schemas']['SetDungeonField']
export type SetEdges = components['schemas']['SetEdges']
export type SetEncounter = components['schemas']['SetEncounter']
export type SetEntrance = components['schemas']['SetEntrance']
export type SetFeature = components['schemas']['SetFeature']
export type SetTownField = components['schemas']['SetTownField']
export type SetTrap = components['schemas']['SetTrap']
export type SetTreasure = components['schemas']['SetTreasure']
export type SetWandering = components['schemas']['SetWandering']
export type SniffResult = components['schemas']['SniffResult']
export type StatusResponse = components['schemas']['StatusResponse']
export type SubtreeChange = components['schemas']['SubtreeChange']
export type TimeUnit = components['schemas']['TimeUnit']
export type TownSpec = components['schemas']['TownSpec']
export type TransitionSpec = components['schemas']['TransitionSpec']
export type TrapEffect = components['schemas']['TrapEffect']
export type TrapSpec = components['schemas']['TrapSpec']
export type TreasureTypeCatalogResponse = components['schemas']['TreasureTypeCatalogResponse']
export type ValuableSpec = components['schemas']['ValuableSpec']
export type WanderingSpec = components['schemas']['WanderingSpec']

// Phase 5: the forge review surface — forge's own contracts riding the
// generated types, never hand-mirrored.
export type ForgeState = components['schemas']['ForgeState']
export type ExtractionReport = components['schemas']['ExtractionReport']
export type AreaReport = components['schemas']['AreaReport']
export type MonsterSummary = components['schemas']['MonsterSummary']
export type CustomMonsterRecord = components['schemas']['CustomMonsterRecord']
export type LintFinding = components['schemas']['LintFinding']
export type RunMeta = components['schemas']['RunMeta']
export type StageStatus = components['schemas']['StageStatus']
export type ConversionSettings = components['schemas']['ConversionSettings']
export type Overrides = components['schemas']['Overrides']
export type AreaOverride = components['schemas']['AreaOverride']
export type GeometryOverride = components['schemas']['GeometryOverride']
export type MonsterOverride = components['schemas']['MonsterOverride']
export type StatBlockOverride = components['schemas']['StatBlockOverride']
export type TownOverride = components['schemas']['TownOverride']
export type ModuleOverride = components['schemas']['ModuleOverride']
export type StatBlockPatch = components['schemas']['StatBlockPatch']
export type EditorSidecar = components['schemas']['EditorSidecar']
export type SidecarProvenance = components['schemas']['SidecarProvenance']
export type ViewState = components['schemas']['ViewState']
export type ReviewMark = components['schemas']['ReviewMark']
export type ZoomPan = components['schemas']['ZoomPan']
export type ForgeOverridesRequest = components['schemas']['ForgeOverridesRequest']
export type SidecarPatchRequest = components['schemas']['SidecarPatchRequest']

// Phase 6: the conversion surface — forge's own `Stage`, `StageStatus`,
// `TokenUsage`, and `CostEstimate` riding the generated types, never mirrored.
export type Stage = components['schemas']['Stage']
export type ConversionState = components['schemas']['ConversionState']
export type ConversionStageRow = components['schemas']['ConversionStageRow']
export type CostEstimate = components['schemas']['CostEstimate']
export type CreateConversionRequest = components['schemas']['CreateConversionRequest']
export type RunConversionRequest = components['schemas']['RunConversionRequest']
export type PreviewResult = components['schemas']['PreviewResult']
export type PreviewLevel = components['schemas']['PreviewLevel']
export type ProviderStatus = components['schemas']['ProviderStatus']
export type ProviderFieldStatus = components['schemas']['ProviderFieldStatus']
export type ProviderSettingsRequest = components['schemas']['ProviderSettingsRequest']

// The conversion lifecycle, as ConversionState actually carries it — the union
// the screen discriminates on.
export type ConversionStateName = ConversionState['state']
export type ConversionKind = ConversionState['kind']

// The discriminated op union, as OpBatch actually carries it.
export type AnyEditOp = OpBatch['ops'][number]

// The override-level edit union, as the forge overrides route carries it.
export type AnyOverrideEdit = ForgeOverridesRequest['edits'][number]

// The sidecar patch union, as the sidecar route carries it.
export type AnySidecarPatch = SidecarPatchRequest['patches'][number]

// The encounter-table entry union, as a row actually carries it.
export type EncounterEntry = EncounterTableRow['entry']

// The cell address shared by every geometry surface: a two-tuple, as osrlib
// serializes Position.
export type Position = [number, number]
